### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by obliviusm** [vetaluga/Slider01#1]
Learn how to use github markdown:
https://guides.github.com/features/mastering-markdown/
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://help.github.com/articles/about-writing-and-formatting-on-github/

And make your readme clean and pretty

**Comment by vetaluga** [comment]
I did. I did not read all. I understood how it is working.

**Comment by obliviusm** [comment]
Looks almost good. Please, make ordered list for first and second slider. similar to the unordered list of links below. now it's not a list but just two paragraphs.

**Comment by vetaluga** [comment]
Do I understood correctly? I did.

**Comment by obliviusm** [comment]
No. It doesn't have indentation on the left side like list with links

**Comment by vetaluga** [comment]
Did I do it right?

**Comment by obliviusm** [comment]
Much better. closing
